services:
    iiwa_ros2_ws:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                MAKEFLAGS: -j4
                PARALLELWORKERS: 4
        container_name: iiwa_ros2_container
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            # to transport X11 application window
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
        volumes:
            # for USB devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # ros2 dir
            - ./yaml:/yaml
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/humble/setup.bash && cd /root/ros2_ws && colcon build --executor parallel --symlink-install --mixin release && source /root/ros2_ws/install/setup.bash && bash"
